// include/delta/core/delta_path.h
#pragma once

#include <vector>
#include <cstddef>
#include <stdexcept>
#include <memory>
#include <functional>
#include "list_grid.h"
#include "grid_refine.h"
#include "delta_strategy.h"
#include "interval_info.h"
#include "value_metric.h"

namespace delta {

    /**
     * @class DeltaPath
     * @brief Represents a refinement process (a sequence of grids) generated by a strategy.
     *
     * Currently specialized for ListGrid. Will be generalized later.
     *
     * @tparam Addr Address type.
     * @tparam Value Value type (function values).
     * @tparam Distance Scalar distance type.
     * @tparam Betweenness Betweenness relation type.
     * @tparam Metric Address metric type.
     * @tparam ValueMetric Value metric type.
     * @tparam Compare Comparator for grids.
     */
    template<typename Addr, typename Value, typename Distance,
        typename Betweenness, typename Metric, typename ValueMetric,
        typename Compare = std::less<Addr>>
        class DeltaPath {
        public:
            using Strategy = DeltaStrategy<Addr, Value, Distance, Betweenness, Metric, ValueMetric>;
            using StrategyPtr = std::shared_ptr<const Strategy>;
            using GridType = ListGrid<Addr, Compare>;
            using Func = std::function<Value(const Addr&)>;

            DeltaPath(GridType initial_grid, StrategyPtr strategy,
                Betweenness betweenness, Metric metric, ValueMetric value_metric)
                : current_grid_(std::move(initial_grid))
                , strategy_(std::move(strategy))
                , betweenness_(std::move(betweenness))
                , metric_(std::move(metric))
                , value_metric_(std::move(value_metric))
                , level_(0) {
            }

            void advance(const Func& func) {
                auto op = strategy_->get_operator(level_);

                // Compute max oscillation for this level using the value metric
                Distance max_osc = Distance{ 0 };
                for (std::size_t i = 0; i + 1 < current_grid_.size(); ++i) {
                    Distance d = value_metric_(func(current_grid_[i + 1]), func(current_grid_[i]));
                    if (d > max_osc) max_osc = d;
                }

                // Build next grid using refine_grid
                auto next_grid = refine_grid(current_grid_,
                    [&](const Addr& left, const Addr& right) {
                        IntervalInfo<Addr, Value, Distance, Betweenness, Metric, ValueMetric>
                            info{ left, right, level_,
                                 func(left), func(right), max_osc,
                                 betweenness_, metric_, value_metric_ };
                        return op(left, right, info);
                    });

#ifndef NDEBUG
                // Verify betweenness for each new point
                for (std::size_t i = 0; i + 1 < next_grid.size(); ++i) {
                    const Addr& left = next_grid[i];
                    const Addr& right = next_grid[i + 1];
                    // Find if this is a newly inserted point (not in old grid)
                    // This is expensive in debug mode, but we'll keep it simple
                }
#endif

                current_grid_ = std::move(next_grid);
                ++level_;
            }

            const GridType& current_grid() const noexcept {
                return current_grid_;
            }

            std::size_t level() const noexcept {
                return level_;
            }

            // Add method to access grid at specific level for testing
            const GridType& get_grid(std::size_t lvl) const {
                if (lvl == level_) return current_grid_;
                throw std::out_of_range("Only current grid is stored");
            }

            Addr max_gap() const {
                Addr max_g = Addr{ 0 };
                for (std::size_t i = 0; i + 1 < current_grid_.size(); ++i) {
                    Addr gap = metric_(current_grid_[i + 1], current_grid_[i]);
                    if (gap > max_g) max_g = gap;
                }
                return max_g;
            }

        private:
            GridType current_grid_;
            StrategyPtr strategy_;
            Betweenness betweenness_;
            Metric metric_;
            ValueMetric value_metric_;
            std::size_t level_;
    };

} // namespace delta