// include/delta/core/delta_path.h
#pragma once

#include <vector>
#include <cstddef>
#include <stdexcept>
#include "grid.h"
#include "delta_strategy.h"
#include "interval_info.h"

namespace delta {

    /**
     * @class DeltaPath
     * @brief Represents a refinement process (a sequence of grids) generated by a strategy.
     *
     * @tparam Addr Address type.
     * @tparam Value Value type (function values).
     * @tparam Distance Scalar distance type.
     * @tparam Betweenness Betweenness relation type.
     * @tparam Metric Address metric type.
     * @tparam ValueMetric Value metric type.
     * @tparam Compare Comparator for grids (default std::less<Addr>).
     */
    template<typename Addr, typename Value, typename Distance,
        typename Betweenness, typename Metric, typename ValueMetric,
        typename Compare = std::less<Addr>>
        class DeltaPath {
        public:
            using Strategy = DeltaStrategy<Addr, Value, Distance, Betweenness, Metric, ValueMetric>;
            using StrategyPtr = std::shared_ptr<const Strategy>;
            using GridType = Grid<Addr, Compare>;
            using Func = std::function<Value(const Addr&)>;  // Operational function at current level

            /**
             * @brief Construct a new DeltaPath.
             * @param initial_grid The starting grid S₀.
             * @param strategy The strategy that supplies operators.
             * @param betweenness The betweenness relation.
             * @param metric The metric on addresses.
             * @param value_metric The metric on function values.
             */
            DeltaPath(GridType initial_grid, StrategyPtr strategy,
                Betweenness betweenness, Metric metric, ValueMetric value_metric)
                : grids_{ std::move(initial_grid) }
                , strategy_(std::move(strategy))
                , betweenness_(std::move(betweenness))
                , metric_(std::move(metric))
                , value_metric_(std::move(value_metric))
                , level_(0) {
            }

            /**
             * @brief Advance one refinement level.
             * @param func A callable that returns the value of the operational function at any address
             *             of the current grid.
             *
             * The new grid is computed by applying the operator from the strategy to each consecutive pair,
             * verifying the betweenness condition using the stored betweenness relation.
             */
            void advance(const Func& func) {
                const auto& current = grids_.back();
                auto op = strategy_->get_operator(level_);

                // Pre‑compute max oscillation for this level using the value metric
                Distance max_osc = Distance{ 0 };
                const auto& data = current.data();
                for (std::size_t i = 0; i + 1 < data.size(); ++i) {
                    Distance d = value_metric_(func(data[i + 1]), func(data[i]));
                    if (d > max_osc) max_osc = d;
                }

                std::vector<Addr> next;
                next.reserve(2 * data.size() - 1);

                for (std::size_t i = 0; i + 1 < data.size(); ++i) {
                    const Addr& left = data[i];
                    const Addr& right = data[i + 1];
                    Value f_left = func(left);
                    Value f_right = func(right);

                    IntervalInfo<Addr, Value, Distance, Betweenness, Metric, ValueMetric>
                        info{ left, right, level_, f_left, f_right, max_osc,
                             betweenness_, metric_, value_metric_ };
                    Addr mid = op(left, right, info);

#ifndef NDEBUG
                    // Verify the betweenness condition using the stored betweenness relation
                    if (!betweenness_(left, mid, right)) {
                        throw std::logic_error("DeltaPath: operator returned a value not strictly between endpoints according to betweenness relation");
                    }
#endif

                    next.push_back(left);
                    next.push_back(std::move(mid));
                }
                next.push_back(data.back());

                grids_.emplace_back(std::move(next), current.comparator());
                ++level_;
            }

            /**
             * @brief Get the current grid (last generated).
             */
            const GridType& current_grid() const noexcept {
                return grids_.back();
            }

            /**
             * @brief Get the current level (0‑based index).
             */
            std::size_t level() const noexcept {
                return level_;
            }

            /**
             * @brief Get all grids generated so far (including initial).
             */
            const std::vector<GridType>& grids() const noexcept {
                return grids_;
            }

            /**
             * @brief Compute the maximal gap δ_n of the current grid using the stored address metric.
             */
            Addr max_gap() const {
                const auto& data = current_grid().data();
                Addr max_g = Addr{ 0 };
                for (std::size_t i = 0; i + 1 < data.size(); ++i) {
                    Addr gap = metric_(data[i + 1], data[i]);  // distance between consecutive addresses
                    if (gap > max_g) max_g = gap;
                }
                return max_g;
            }

        private:
            std::vector<GridType> grids_;
            StrategyPtr strategy_;
            Betweenness betweenness_;
            Metric metric_;
            ValueMetric value_metric_;
            std::size_t level_;
    };

} // namespace delta